package com.limitlessvirtual.droidsembla.models;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table TICKET.
 */
public class Ticket {

    private Long id;
    private String summary;
    private String status;
    private Integer number;
    private long projectId;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public Ticket() {
    }

    public Ticket(Long id) {
        this.id = id;
    }

    public Ticket(Long id, String summary, String status, Integer number, long projectId) {
        this.id = id;
        this.summary = summary;
        this.status = status;
        this.number = number;
        this.projectId = projectId;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getSummary() {
        return summary;
    }

    public void setSummary(String summary) {
        this.summary = summary;
    }

    public String getStatus() {
        return status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    public Integer getNumber() {
        return number;
    }

    public void setNumber(Integer number) {
        this.number = number;
    }

    public long getProjectId() {
        return projectId;
    }

    public void setProjectId(long projectId) {
        this.projectId = projectId;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
